export { PROFILE_PARSE_SYSTEM_PROMPT, SCENARIO_PARSE_SYSTEM_PROMPT } from './input.js';
export { PLAN_NARRATION_SYSTEM_PROMPT, SCENARIO_NARRATION_SYSTEM_PROMPT } from './output.js';
export { MONEY_EVENT_PARSE_SYSTEM_PROMPT, MOBILITY_NARRATION_SYSTEM_PROMPT } from './mobility.js';

export const PROMPT_VERSION = '1.0.0';
