import type { PermittedAction } from '@copia/types';

export const GB_PERMITTED_ACTIONS: PermittedAction[] = [
  {
    id: 'gb-bank-deposit',
    name: 'UK Bank Deposit',
    category: 'source_country',
    country: 'GB',
    permitted: true,
    restrictions: ['No restrictions on depositing funds in UK bank accounts', 'FSCS protection up to £85,000 per institution'],
    taxConsequences: ['Interest income taxable — Personal Savings Allowance: £1,000 (basic rate) / £500 (higher rate)'],
    filingObligations: ['Self Assessment if total income exceeds thresholds'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'gb-bank-1',
        sourceType: 'regulation',
        title: 'UK Banking Regulations',
        reference: 'FCA banking regulations; FSCS Deposit Protection',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'GB',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'gb-equities',
    name: 'UK Listed Equities',
    category: 'source_country',
    country: 'GB',
    permitted: true,
    restrictions: ['No restrictions on purchasing UK or foreign equities', '0.5% Stamp Duty Reserve Tax on UK share purchases'],
    taxConsequences: ['Dividends: £1,000 allowance then 8.75% / 33.75% / 39.35%', 'CGT: £6,000 AEA then 10% / 20%'],
    filingObligations: ['Self Assessment for capital gains and dividends above allowances'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'gb-eq-1',
        sourceType: 'statute',
        title: 'UK Capital Gains and Dividend Tax',
        reference: 'TCGA 1992; ITTOIA 2005 Part 4',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'GB',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'gb-isa',
    name: 'Individual Savings Account (ISA)',
    category: 'source_country',
    country: 'GB',
    permitted: true,
    restrictions: [
      'Must be UK tax resident to open/contribute',
      'Annual contribution limit: £20,000 across all ISA types',
      'Non-residents cannot contribute but can hold existing ISAs',
    ],
    taxConsequences: ['Tax-free growth and income within ISA wrapper', 'No CGT or income tax on ISA returns'],
    filingObligations: ['None — ISA income/gains not reportable on Self Assessment'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'gb-isa-1',
        sourceType: 'statute',
        title: 'ISA Regulations',
        reference: 'Individual Savings Account Regulations 1998 (SI 1998/1870)',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'GB',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'gb-sipp',
    name: 'Self-Invested Personal Pension (SIPP)',
    category: 'source_country',
    country: 'GB',
    permitted: true,
    restrictions: [
      'Annual allowance: £60,000 (2023-24)',
      'Lifetime allowance abolished from April 2024',
      'Minimum pension age 55 (rising to 57 in 2028)',
      'Non-residents: limited contributions but can retain existing SIPPs',
    ],
    taxConsequences: [
      'Tax relief on contributions at marginal rate',
      '25% tax-free lump sum on drawdown',
      'Remaining drawdown taxed as income',
      'IHT-free if death before 75',
    ],
    filingObligations: ['Self Assessment for pension income drawdown'],
    repatriability: 'partial',
    timeConstraints: 'Cannot access before age 55 (57 from 2028)',
    citations: [
      {
        id: 'gb-sipp-1',
        sourceType: 'statute',
        title: 'Pension Tax Relief',
        reference: 'Finance Act 2004 Part 4; Pension Schemes Act 2015',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'GB',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'gb-property',
    name: 'UK Property Purchase',
    category: 'source_country',
    country: 'GB',
    permitted: true,
    restrictions: [
      'No restrictions on property ownership by non-residents',
      'Non-resident surcharge: 2% additional SDLT',
      'Additional property surcharge: 3% SDLT',
      'ATED applies if held through company (£3,700+ annually)',
    ],
    taxConsequences: [
      'SDLT: progressive rates 0-12% (+ 2% non-resident, + 3% additional property)',
      'Rental income: 20-45% income tax',
      'CGT on disposal: 18% / 28% (residential)',
    ],
    filingObligations: ['SDLT return within 14 days', 'Self Assessment for rental income', 'CGT return within 60 days of completion'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'gb-prop-1',
        sourceType: 'statute',
        title: 'SDLT and Property Taxation',
        reference: 'Finance Act 2003 Part 4 (SDLT); TCGA 1992',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'GB',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'gb-spouse-gift',
    name: 'Gift to Spouse/Civil Partner',
    category: 'source_country',
    country: 'GB',
    permitted: true,
    restrictions: [
      'Unlimited spousal exemption for IHT (both UK-domiciled)',
      'Limited to £325,000 if recipient spouse is non-UK-domiciled',
      'Inter-spouse transfers are CGT-free (no gain/no loss basis)',
    ],
    taxConsequences: ['No IHT (unlimited exemption)', 'No CGT on transfer', 'Recipient inherits original cost base for CGT'],
    filingObligations: ['None unless non-domiciled spouse limit applies'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'gb-spouse-1',
        sourceType: 'statute',
        title: 'Spousal IHT Exemption',
        reference: 'IHTA 1984 §18; TCGA 1992 §58',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'GB',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'gb-pet-gift',
    name: 'Gift to Children (PET)',
    category: 'source_country',
    country: 'GB',
    permitted: true,
    restrictions: [
      'Potentially Exempt Transfer — fully exempt if donor survives 7 years',
      'Taper relief applies after 3 years if donor dies within 7',
      '£3,000 annual exemption; £250 small gifts exemption per recipient',
    ],
    taxConsequences: ['No immediate IHT', 'IHT at 40% (with taper relief) if donor dies within 7 years', 'CGT disposal if gifting assets (not cash)'],
    filingObligations: ['Record gift and date for 7-year tracking', 'IHT400 if chargeable on death within 7 years'],
    repatriability: 'full',
    timeConstraints: '7-year survival period for full IHT exemption',
    citations: [
      {
        id: 'gb-pet-1',
        sourceType: 'statute',
        title: 'PET Rules',
        reference: 'IHTA 1984 §3A; §7(4)',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'GB',
      },
    ],
    confidence: 'statutory',
  },
];
