import type { PermittedAction } from '@copia/types';

export const IN_PERMITTED_ACTIONS: PermittedAction[] = [
  {
    id: 'in-nro-fd',
    name: 'NRO Fixed Deposit',
    category: 'source_country',
    country: 'IN',
    permitted: true,
    restrictions: [
      'Must use NRO account',
      'Interest income subject to TDS at 30% (plus surcharge and cess)',
      'Repatriation of principal + interest capped at USD 1M/year',
    ],
    taxConsequences: ['TDS 30% on interest income', 'Taxable in India at slab rates'],
    filingObligations: ['ITR filing as NRI', 'Form 15CA/15CB for repatriation'],
    repatriability: 'partial',
    timeConstraints: null,
    citations: [
      {
        id: 'in-nro-fd-1',
        sourceType: 'regulation',
        title: 'FEMA Deposit Regulations',
        reference: 'FEMA (Deposit) Regulations 2016',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'IN',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'in-mutual-funds',
    name: 'Mutual Fund Investment',
    category: 'source_country',
    country: 'IN',
    permitted: true,
    restrictions: [
      'NRIs can invest in most mutual funds (equity, debt, hybrid)',
      'US/Canada NRIs face additional restrictions — many AMCs do not accept',
      'Must use NRO or NRE account for investment',
      'KYC with PAN and overseas address required',
    ],
    taxConsequences: [
      'Equity LTCG above INR 1.25 lakh taxed at 12.5%',
      'Equity STCG taxed at 20%',
      'Debt fund gains taxed at slab rates',
      'TDS applicable on redemption proceeds for NRIs',
    ],
    filingObligations: ['ITR filing for capital gains', 'Form 15CA/15CB on repatriation'],
    repatriability: 'partial',
    timeConstraints: null,
    citations: [
      {
        id: 'in-mf-1',
        sourceType: 'regulation',
        title: 'SEBI Mutual Fund Regulations',
        reference: 'SEBI (Mutual Funds) Regulations 1996; FEMA Act 1999',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'IN',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'in-pis-equities',
    name: 'Portfolio Investment Scheme (PIS) — Listed Equities',
    category: 'source_country',
    country: 'IN',
    permitted: true,
    restrictions: [
      'Must register with designated bank under RBI PIS scheme',
      'Single NRI: max 5% of paid-up capital of a company',
      'All NRIs combined: max 10% (can be raised to 24% by company resolution)',
      'Must use NRE or NRO designated account',
    ],
    taxConsequences: [
      'LTCG above INR 1.25 lakh at 12.5%',
      'STCG at 20%',
      'STT applicable on exchange transactions',
      'TDS on sale proceeds for NRI accounts',
    ],
    filingObligations: ['ITR filing', 'PIS reporting to designated bank', 'Form 15CA/15CB on repatriation'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'in-pis-1',
        sourceType: 'regulation',
        title: 'RBI Portfolio Investment Scheme',
        reference: 'RBI Master Direction – Portfolio Investment Scheme; FEMA (Non-debt Instruments) Rules 2019',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'IN',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'in-property-purchase',
    name: 'Residential/Commercial Property Purchase',
    category: 'source_country',
    country: 'IN',
    permitted: true,
    restrictions: [
      'NRIs can purchase residential and commercial property',
      'Agricultural land, plantation property, and farmhouse are PROHIBITED for NRIs',
      'Payment must be from NRE/NRO/FCNR account or inward remittance',
      'Max two residential properties under Section 54 reinvestment',
    ],
    taxConsequences: [
      'Stamp duty 5-7% (varies by state)',
      'Rental income taxable at slab rates (30% TDS)',
      'LTCG on sale: 20% with indexation',
      'Section 54 reinvestment exemption available',
    ],
    filingObligations: ['Property registration', 'ITR for rental income and capital gains', 'Form 15CA/15CB on repatriation of sale proceeds'],
    repatriability: 'partial',
    timeConstraints: 'Section 54 reinvestment: purchase within 1 year before or 2 years after sale',
    citations: [
      {
        id: 'in-prop-1',
        sourceType: 'statute',
        title: 'FEMA Immovable Property Regulations',
        reference: 'FEMA (Non-debt Instruments) Rules 2019; Income Tax Act 1961 §54',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'IN',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'in-agricultural-land',
    name: 'Agricultural Land Purchase',
    category: 'source_country',
    country: 'IN',
    permitted: false,
    restrictions: [
      'NRIs and OCIs are PROHIBITED from purchasing agricultural land, plantation property, or farmhouses',
      'Can only be acquired by inheritance — not purchase or gift from non-relative',
    ],
    taxConsequences: [],
    filingObligations: [],
    repatriability: 'none',
    timeConstraints: null,
    citations: [
      {
        id: 'in-agri-1',
        sourceType: 'statute',
        title: 'FEMA Immovable Property Restriction',
        reference: 'FEMA (Non-debt Instruments) Rules 2019, Rule 21',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'IN',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'in-section-54ec-bonds',
    name: 'Section 54EC Bonds (NHAI/REC)',
    category: 'source_country',
    country: 'IN',
    permitted: true,
    restrictions: [
      'LTCG exemption up to INR 50 lakh per financial year',
      'Must invest within 6 months of property transfer',
      '5-year lock-in period — bonds cannot be transferred or pledged',
      'Available from NHAI, REC, IRFC, PFC',
    ],
    taxConsequences: [
      'Exempts LTCG up to INR 50 lakh from tax',
      'Interest on bonds is taxable at slab rates',
    ],
    filingObligations: ['Claim exemption in ITR under Section 54EC'],
    repatriability: 'partial',
    timeConstraints: 'Must invest within 6 months of transfer date; 5-year lock-in',
    citations: [
      {
        id: 'in-54ec-1',
        sourceType: 'statute',
        title: 'Section 54EC Capital Gains Bonds',
        reference: 'Income Tax Act 1961 §54EC',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'IN',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'in-section-54-reinvest',
    name: 'Section 54 Reinvestment in Residential Property',
    category: 'source_country',
    country: 'IN',
    permitted: true,
    restrictions: [
      'LTCG on sale of residential property exempt if reinvested in new residential property',
      'Maximum one residential property (up to INR 10 crore)',
      'Purchase within 1 year before or 2 years after sale, or construction within 3 years',
      'If not reinvested by ITR deadline, deposit in Capital Gains Account Scheme',
    ],
    taxConsequences: ['Full LTCG exemption if conditions met', 'Partial exemption for partial reinvestment under §54F'],
    filingObligations: ['Claim in ITR', 'Capital Gains Account Scheme deposit if applicable'],
    repatriability: 'none',
    timeConstraints: 'Purchase: 1yr before / 2yr after; Construction: 3yr after',
    citations: [
      {
        id: 'in-s54-1',
        sourceType: 'statute',
        title: 'Section 54 Reinvestment',
        reference: 'Income Tax Act 1961 §54',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'IN',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'in-gift-to-relatives',
    name: 'Gift to Relatives',
    category: 'source_country',
    country: 'IN',
    permitted: true,
    restrictions: [
      'Gifts from NRO account to relatives (as defined in §56(2)(x)) are permitted',
      'Within the USD 1M/year NRO repatriation limit',
      'Relative definition: spouse, siblings, lineal ascendants/descendants and their spouses',
    ],
    taxConsequences: ['Gifts from relatives are exempt under §56(2)(x)', 'No TDS on gifts to resident relatives from NRO'],
    filingObligations: ['ITR disclosure', 'Gift deed recommended for documentation'],
    repatriability: 'partial',
    timeConstraints: null,
    citations: [
      {
        id: 'in-gift-1',
        sourceType: 'statute',
        title: 'Section 56(2)(x) Gift Exemption',
        reference: 'Income Tax Act 1961 §56(2)(x)',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'IN',
      },
    ],
    confidence: 'statutory',
  },
];
