import type { PermittedAction } from '@copia/types';

export const PT_PERMITTED_ACTIONS: PermittedAction[] = [
  {
    id: 'pt-bank-deposit',
    name: 'Portuguese Bank Deposit',
    category: 'source_country',
    country: 'PT',
    permitted: true,
    restrictions: [
      'EU free movement of capital — no restrictions',
      'Deposit Guarantee Fund: EUR 100,000 per depositor per bank',
    ],
    taxConsequences: ['Interest income: flat 28% withholding or englobamento election', 'NHR holders: foreign-source interest may be exempt'],
    filingObligations: ['Annual IRS return (Modelo 3)'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'pt-bank-1',
        sourceType: 'statute',
        title: 'Portuguese Interest Income Tax',
        reference: 'CIRS Art. 71; EU Treaty Art. 63',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'PT',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'pt-property',
    name: 'Portuguese Property Purchase',
    category: 'source_country',
    country: 'PT',
    permitted: true,
    restrictions: [
      'No restrictions on foreign ownership of Portuguese property',
      'Golden Visa programme no longer available for real estate (since Oct 2023)',
    ],
    taxConsequences: [
      'IMT (transfer tax): progressive rates 0-7.5% (residential) / flat 6.5% (other)',
      'Stamp duty: 0.8% on property value',
      'Annual IMI (property tax): 0.3-0.45% urban / 0.8% rural',
      'AIMI (additional stamp duty) on properties above EUR 600K',
      'Rental income: 28% flat or englobamento',
    ],
    filingObligations: ['IMT declaration before deed', 'Annual IRS for rental income', 'IMI paid annually'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'pt-prop-1',
        sourceType: 'statute',
        title: 'Portuguese Property Tax',
        reference: 'CIMT (Codigo do IMT); CIMI (Codigo do IMI)',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'PT',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'pt-nhr-foreign-income',
    name: 'NHR Foreign Income Exemption',
    category: 'destination_country',
    country: 'PT',
    permitted: true,
    restrictions: [
      'Only available to existing NHR beneficiaries (regime closed Jan 2024)',
      'Must have been non-resident in Portugal for 5 years prior',
      '10-year duration from registration',
      'Foreign-source pension income: flat 10% rate',
    ],
    taxConsequences: [
      'Foreign dividends, interest, royalties: exempt if taxable in source (per DTA)',
      'Foreign employment income from high-value activities: flat 20%',
      'Foreign pension income: 10% flat rate',
      'Portuguese-source income: normal progressive rates (except qualifying employment at 20%)',
    ],
    filingObligations: ['Annual IRS return with NHR status claimed', 'Annex L for foreign income'],
    repatriability: 'full',
    timeConstraints: '10-year regime — applies for existing holders only',
    citations: [
      {
        id: 'pt-nhr-1',
        sourceType: 'statute',
        title: 'NHR Regime',
        reference: 'Decreto-Lei 249/2009; CIRS Art. 81; Lei 82/2023 (closure)',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'PT',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'pt-eu-transfer',
    name: 'EU/EEA Cross-Border Transfer',
    category: 'third_country',
    country: 'PT',
    permitted: true,
    restrictions: [
      'EU Treaty Art. 63 guarantees free movement of capital',
      'SEPA transfers within EU — no additional fees for EUR transfers',
      'Transfers above EUR 12,500 may trigger reporting to Banco de Portugal',
    ],
    taxConsequences: ['No withholding on outbound transfers', 'Income earned on transferred funds taxable in country of residence'],
    filingObligations: ['Banco de Portugal reporting for large transfers', 'Anti-money-laundering documentation for transactions above EUR 15,000'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'pt-eu-1',
        sourceType: 'treaty',
        title: 'EU Free Movement of Capital',
        reference: 'TFEU Art. 63; SEPA Regulation (EU) 260/2012',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'PT',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'pt-family-gift',
    name: 'Gift to Close Family',
    category: 'source_country',
    country: 'PT',
    permitted: true,
    restrictions: [
      'Gifts to spouse, descendants, ascendants: fully exempt from stamp duty',
      'Gifts to others: 10% Imposto do Selo',
      'Forced heirship rules may apply to lifetime gifts that impair legitimate portion',
    ],
    taxConsequences: ['Exempt if to direct family', '10% stamp duty if to non-exempt recipients'],
    filingObligations: ['Stamp duty declaration for non-exempt gifts', 'Property gifts require notarial deed'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'pt-gift-1',
        sourceType: 'statute',
        title: 'Portuguese Gift Taxation',
        reference: 'CIS Art. 6(e); CIS General Table Item 1.2',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'PT',
      },
    ],
    confidence: 'statutory',
  },
];
