import type { PermittedAction } from '@copia/types';

export const US_PERMITTED_ACTIONS: PermittedAction[] = [
  {
    id: 'us-bank-deposit',
    name: 'US Bank/Brokerage Deposit',
    category: 'source_country',
    country: 'US',
    permitted: true,
    restrictions: ['No restrictions on deposits', 'FDIC insurance up to $250,000 per depositor per bank'],
    taxConsequences: ['Interest income taxable at ordinary income rates', 'NRAs: 30% withholding on US-source interest (treaty may reduce)'],
    filingObligations: ['Form 1099-INT reported by bank', 'FBAR/FATCA if foreign person with US accounts'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'us-bank-1',
        sourceType: 'regulation',
        title: 'US Banking and Tax Reporting',
        reference: 'IRC §871(a); FDIC Insurance Rules',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'US',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'us-equities',
    name: 'US Securities Investment',
    category: 'source_country',
    country: 'US',
    permitted: true,
    restrictions: ['No restrictions for domestic or foreign investors', 'SEC reporting for positions >5% of public company'],
    taxConsequences: [
      'LTCG: 0% / 15% / 20% (holding >12 months)',
      'STCG: ordinary income rates',
      'Qualified dividends: 0% / 15% / 20%',
      'NRA: 30% withholding on dividends (treaty may reduce)',
    ],
    filingObligations: ['Form 1040 Schedule D', 'Form 8949 for detailed transactions', 'Form 1042-S for NRA withholding'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'us-eq-1',
        sourceType: 'statute',
        title: 'US Capital Gains Tax',
        reference: 'IRC §1(h); IRC §1222; IRC §871(a)',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'US',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'us-property',
    name: 'US Real Property',
    category: 'source_country',
    country: 'US',
    permitted: true,
    restrictions: [
      'No restrictions on foreign ownership of US real property',
      'Some states restrict agricultural land ownership by foreign persons',
      'FIRPTA withholding on disposition by foreign persons',
    ],
    taxConsequences: [
      'FIRPTA: 15% withholding on gross proceeds for foreign sellers',
      'State and local property taxes',
      'Rental income taxable (can elect net basis under IRC §871(d))',
      'US-situs for estate tax purposes',
    ],
    filingObligations: ['Form 8288 (FIRPTA withholding)', 'Form 1040-NR for rental income', 'State property tax filings'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'us-prop-1',
        sourceType: 'statute',
        title: 'FIRPTA and US Property Rules',
        reference: 'IRC §897 (FIRPTA); IRC §871(d)',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'US',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'us-form-3520-reporting',
    name: 'Form 3520 Reporting (Foreign Gifts >$100K)',
    category: 'destination_country',
    country: 'US',
    permitted: true,
    restrictions: [
      'US persons receiving foreign gifts/bequests exceeding $100,000 must file Form 3520',
      'Not a tax — purely informational reporting',
      'Failure to file carries 5% per month penalty on unreported amount (up to 25%)',
    ],
    taxConsequences: ['No tax on receipt of foreign gift/inheritance', 'Income subsequently earned on gifted assets is taxable'],
    filingObligations: [
      'Form 3520 due with tax return (April 15, extension to October 15)',
      'Separate Form 3520 for each foreign trust transaction',
    ],
    repatriability: 'full',
    timeConstraints: 'Form 3520 due by tax return deadline',
    citations: [
      {
        id: 'us-3520-1',
        sourceType: 'statute',
        title: 'Form 3520 Foreign Gift Reporting',
        reference: 'IRC §6039F; IRS Form 3520 Instructions',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'US',
      },
    ],
    confidence: 'statutory',
  },
  {
    id: 'us-pfic',
    name: 'Passive Foreign Investment Company (PFIC) Holdings',
    category: 'destination_country',
    country: 'US',
    permitted: true,
    restrictions: [
      'US persons holding PFICs face punitive tax treatment unless election made',
      'QEF or mark-to-market election recommended to avoid excess distribution regime',
      'Many foreign mutual funds qualify as PFICs',
    ],
    taxConsequences: [
      'Default: excess distribution regime — gains taxed at highest marginal rate + interest charge',
      'QEF election: current inclusion of pro rata share of income',
      'Mark-to-market: annual gain/loss recognition',
    ],
    filingObligations: ['Form 8621 for each PFIC held', 'Annual filing required even if no distributions'],
    repatriability: 'full',
    timeConstraints: null,
    citations: [
      {
        id: 'us-pfic-1',
        sourceType: 'statute',
        title: 'PFIC Tax Rules',
        reference: 'IRC §1291-1298; IRS Form 8621',
        url: null,
        confidence: 'statutory',
        asOfDate: '2024-01-01',
        jurisdiction: 'US',
      },
    ],
    confidence: 'statutory',
  },
];
